max_workers: ${CONCURRENCY:100}

AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASS:guest}@${RABBIT_SERVER:localhost}:${RABBIT_PORT:5672}/${RABBIT_VHOST:}

JWT_SECRET: ${JWT_SECRET:super_secret}

WEB_SERVER_ADDRESS: ${SERVER_ADDRESS:0.0.0.0}:${SERVER_PORT:8000}

#DEFAULT_CORS: ${DEFAULT_CORS:"https://findfeatures.io"}
DEFAULT_CORS: ${DEFAULT_CORS:"*"}

REDIS_URL: redis://${REDIS_SERVER:127.0.0.1}:${REDIS_PORT:6379}/${REDIS_DB:0}

ENVIRONMENT: ${ENVIRONMENT:test}